# menu
menu:
  Home: /
  Archives: /archives
  Categories: /categories
  # Tags: /tags
  About: /about
  Selfhosted: /selfhosted

author: Resolmi
favicon: https://static.imlgw.top/blog/fa.png
since: 2017

github_username: imlgw
auto_excerpt_len: 150

# comment extend, support gialk
comment_extend:
    gitalk:
        enable: false
        clientID: # 不安全，不建议使用
        clientSecret: # 
    disqus:
        shortname: imlgw