# menu
menu:
  Home: /
  Archives: /archives
  Categories: /categories
  # Tags: /tags
  About: /about
  Selfhosted: /selfhosted
  Search: /search


author: Resolmi
favicon: https://fav.farm/ğŸŒ§ï¸
since: 2017

github_username: imlgw
auto_excerpt_len: 150

# comment extend, support gialk
comment_extend:
    gitalk:
        enable: false
        clientID: # ä¸å®‰å…¨ï¼Œä¸å»ºè®®ä½¿ç”¨
        clientSecret: # 
    disqus:
        shortname: imlgw